Cypress.Commands.add('registration',(userName,userEmail,password)=>{
cy.contains ("New User Signup!").should("be.visible")
    cy.get ('[data-qa="signup-name"]').type(userName)
    cy.get ('[data-qa="signup-email"]').type(userEmail)
    cy.get ('[data-qa="signup-button"]').click ()
    cy.contains ("Enter Account Information").should ("be.visible")
    cy.get ("#id_gender2").click()
    cy.get ('[data-qa="password"]').type(password)
    cy.get ('[data-qa="days"]').select ("5")
    cy.get ('[data-qa="months"]').select ("12")
    cy.get ('[data-qa="years"]').select ("1980")
    cy.contains ("Sign up for our newsletter!").click ()
    cy.contains ("Receive special offers from our partners!").click ()
    cy.get ('[data-qa="first_name"]').type("Tamari")
    cy.get ('[data-qa="last_name"]').type("Jikia")
    cy.get ('[data-qa="company"]').type("HW")
    cy.get ('[data-qa="address"]').type("Digomi")
    cy.get ('[data-qa="address2"]').type("3 block 18")
    cy.get ('[data-qa="country"]').select ("United States")
    cy.get ('[data-qa="state"]').type("Texas")    
    cy.get ('[data-qa="city"]').type("Chicago")
    cy.get ('[data-qa="zipcode"]').type("60611")
    cy.get ('[data-qa="mobile_number"]').type("595321654")
    cy.get ('[data-qa="create-account"]').click ()
    cy.contains ("Account Created!").should ("be.visible")



})